import pandas as pd
import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Image, Spacer, Paragraph
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm


def report_to_pdf(df: pd.DataFrame, pth: str):
    styles = getSampleStyleSheet()
    title = Paragraph(f"📈 Experiment Results {datetime.datetime.today().strftime('%d.%m.%Y')}", styles["Title"])
    data = [df.columns.tolist()] + df.values.tolist()
    table = Table(data, repeatRows=1)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#4F81BD")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('.FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
    ]))
    centered_style = ParagraphStyle(
    name="Centered",
    parent=styles["Normal"],
    alignment=1,
    fontSize=12
    )

    html_text = (
    'Generated by '
    '<font color="blue"><u><a href="https://github.com/compressa-ai/compressa-perf">'
    'compressa-perf</a></u></font> library'
    )
    text = Paragraph(html_text, centered_style)
    doc = SimpleDocTemplate(pth, pagesize=A4)
    image_path = "logo.png"
    logo = Image(image_path, width=4*cm, height=4*cm)
    elements = [logo, title, text, Spacer(1, 0.5*cm), table]
    doc.build(elements)
