name: Prepare Release
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/.cache/pypoetry/virtualenvs
          installer-parallel: true
      - name: ls
        run: ls -la && ls -la ..
      - name: Install dependencies
        run: poetry install
      - name: Run build
        run: poetry build
